env:
  es2021: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  no-trailing-spaces:
    - error
    - ignoreComments: true
  max-len:
    - error
    - code: 140
  object-curly-spacing:
    - error
    - always
  brace-style:
    - error
    - stroustrup
